---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root

  tasks:
    - name: Collect PCAP file from server
      fetch:
        src: /home/yuri/Documents/PCAP/hoa8.pcap
        dest: /home/yuri/Documents/CPE243_HOA8_1/pcap_dest/
        flat: yes

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Extract executable from PCAP file
      command: "tcpflow -r /home/yuri/Documents/CPE243_HOA8_1/pcap_dest/hoa8.pcap -o /home/yuri/Documents/CPE243_HOA8_1/pcap_out/"
      args:
        creates: /home/yuri/Documents/CPE243_HOA8_1/pcap_out/executable.exe
    - name: Debug .exe file
      command: "cat /home/yuri/Documents/CPE243_HOA8_1/pcap_out/report.xml"
      register: cat_output
      changed_when: false

    - debug:
        var: cat_output.stdout_lines
